### ISSUE TITLE
evaluate csv-to-triples for creating a graph

### ISSUE THREAD

**Issue by mbjones** [data-mobilizsation/knowledge_graph_schema#1]
@graemediack We undertook an earlier project that tried to build a graph from a CSV-formatted set of information that followed a particular template format. This allowed us to quickly create a large graph by manipulating existing information into CSV format, which we could then quickly edit, and then use a python script to convert this into graph format -- we used Turtle for the serialization, but really any of the major graph formats could be output. The code is available here:

https://github.com/Semantic-Observations/obs-models/tree/master/examples/csvtotriples

I worked on this with @amoeba and @mpsaloha and it may be useful to you, depending on the type of input data you have for creating graphs.

Are you trying to do something similar with these graph scripts in this repo? Feel free to close this issue if its not relevant, just trying to bring it to your attention.

**Comment by graemediack** [comment]
Hi @mbjones , thanks for this link I'll check it out. It doesn't sound like this is along the lines of our goal here but I'll browse the repo tomorrow. It's certainly something I'll be checking out with regard to the data loading side of things. With this repo we're looking at abstracting the 'schema' of our salmon graph and working on the finer detail of the core graph - node types, node properties, type-of-node to type-of-node relationships and those relationship properties.
